### ISSUE TITLE
Lost Account - Class::ConfigPHP - Key realurl doesn't exist

### ISSUE THREAD

**Issue by Tr3v0oR** [omarcopires/gesior#17]
Marco,
Está aparecendo o seguinte erro ao tentar usar o a recuperação de senha (Lost Account).
https://pasteboard.co/Jt1XEVt.png

Sendo que configurei da seguinte maneira
https://pasteboard.co/Jt1Ytyr.png

É cagada minha? Ou algum bug mesmo?
Obrigado!

**Comment by talistf** [comment]
@Tr3v0oR, o erro informado está no campo Real URL.

**Comment by talistf** [comment]
@Tr3v0oR pelo que sei o Gmail utiliza as portas 465.
Verifica as configurações e teste novamente.

**Comment by Tr3v0oR** [comment]
> I sent a possible correction, can you check?

Works fine
`$config['site']['realurl'] = $base_url;`
